### ISSUE TITLE
PSET7, Transactions

### ISSUE THREAD

**Issue by albertjose666** [Aesirry/cs50#1]
Finding difficulty in joining users and transactions on phpLiteAdmin. Any suggestions on how to implement transactions table on phpLiteAdmin ? Is it better to do it with SQL3 on the command line ?

**Comment by jpbeltrami** [comment]
Whatever you feel comfortable with. I personally found making new tables with phpLiteAdmin easier because you don't have to retype a command again and again from the beginning if you make a typo or a mistake.

**Comment by albertjose666** [comment]
I typed into the SQL command line in phpLiteAdmin but I keep getting a runtime error when I try to buy shares even tough I have enough cash. Something like this:
RuntimeError: (sqlite3.OperationalError) near ";": syntax error [SQL: "INSERT INTO transactions (symbol, quantity, price, u_id) VALUES ('S', 2, 8.41, 5;"]

I tried buying 2 shares of S&P 500

Clearly there's a suggestion of an error in the syntax but I crosschecked the INSERT syntax with yours and it seems fine. Is it to do with the foreign key ?

Even in phpLiteAdmin how do I assign foreign keys the right way ?

**Comment by albertjose666** [comment]
The following was my Create table SQL command;

CREATE TABLE 'transactions'('tx_id' INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, 'Symbol' TEXT UNIQUE NOT NULL, 'Name' TEXT NOT NULL, 'Shares' INTEGER NOT NULL, 'Price' NUMERIC NOT NULL, 'TOTAL' INTEGER NOT NULL, 'date' DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, 'u_id' INTEGER NOT NULL, FOREIGN KEY (u_id) REFERENCES users(id))

**Comment by albertjose666** [comment]
Actually the run time error was just a simple syntax error but could you please help me with the table 'transactions' implementation. Could you suggest from the SQL code where I might be wrong. Is it related to the foreign key implementation ?

CREATE TABLE 'transactions'('tx_id' INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, 'symbol' TEXT UNIQUE NOT NULL, 'name' TEXT NOT NULL, 'quantity' INTEGER NOT NULL, 'price' NUMERIC NOT NULL, 'total' INTEGER NOT NULL, 'date_time' DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, 'u_id' INTEGER NOT NULL, FOREIGN KEY (u_id) REFERENCES users(id))

**Comment by jpbeltrami** [comment]
``` SQL
CREATE TABLE 'transactions' (
't_id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
'symbol' TEXT NOT NULL, 
'quantity' INTEGER NOT NULL, 
'price' INTEGER NOT NULL, 
'date_time' DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
'u_id' INTEGER NOT NULL)
```
I don't have a foreign key in the transactions table.. It wasn't necessary from what I understood from the problem set..

**Comment by Aesirry** [comment]
I just matched the transactions where the user id matched and also the stock symbol..

**Comment by jpbeltrami** [comment]
In total you are querying the database three times. the first time getting the symbols for the stocks that the user owns. The second for the cash currently held by the user (from another table). and the third time where you sum quantity of the stocks from each symbol that are owned by the user.

That's how I dealt with the index page.

**Comment by albertjose666** [comment]
Thanks for the help but I went with the same SQL code and foreign key. My error was in defining too many or rather the parameters called in my code as Not NULL while creating the table. Dropped the NOT NULL and things worked out. Bur I'll try matching them like u said as well. Thanks again for all the help
